<?php

declare(strict_types=1);

namespace App\Services;

use App\Support\Files;

/**
 * A PHP web server based on serversideup/php.
 *
 * The image is built rather than pulled, because serversideup/php can only
 * change the www-data user's ID at build time. Matching it to the host user
 * keeps the mounted project writable on Linux and WSL.
 */
class Php extends Service
{
    public const array VERSIONS = ['8.1', '8.2', '8.3', '8.4', '8.5'];

    /**
     * Each server variation and the variable that sets its document root.
     */
    public const array SERVERS = [
        'fpm-nginx' => 'NGINX_WEBROOT',
        'fpm-apache' => 'APACHE_DOCUMENT_ROOT',
        'frankenphp' => 'CADDY_SERVER_ROOT',
    ];

    protected const string APP_DIR = '/var/www/html';

    /**
     * A path inside the app: no leading slash and no "..".
     */
    public const string PATH = '#^(?!/)(?!.*\.\.)[A-Za-z0-9._/-]*$#';

    protected const string WP_CLI = 'https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar';

    protected function defaults(): array
    {
        return [
            'version' => '8.4',
            'server' => 'fpm-nginx',
            'webroot' => 'public',
            'project_path' => '.',
            'extensions' => [],
            'wp_cli' => false,
        ];
    }

    protected function rules(): array
    {
        return [
            'version' => ['required', 'in:'.implode(',', self::VERSIONS)],
            'server' => ['required', 'in:'.implode(',', array_keys(self::SERVERS))],
            'webroot' => ['string', 'regex:'.self::PATH],
            'project_path' => ['string', 'regex:'.self::PATH],
            'extensions' => ['list'],
            'extensions.*' => ['string', 'regex:/^[a-z0-9_]+$/'],
            'wp_cli' => ['boolean'],
        ];
    }

    protected function messages(): array
    {
        return [
            'webroot.regex' => 'Expected a path inside the project, such as "public".',
            'project_path.regex' => 'Expected a path inside the app, such as "wp-content/themes/my-theme".',
            'extensions.*.regex' => 'Expected an extension name such as "mysqli".',
        ];
    }

    public static function routes(): bool
    {
        return true;
    }

    /**
     * An unquoted `version: 8.4` parses as a float.
     */
    protected function normalize(array $options): array
    {
        if (is_float($options['version']) || is_int($options['version'])) {
            $options['version'] = sprintf('%.1f', $options['version']);
        }

        return $options;
    }

    public function definition(): array
    {
        return [
            'build' => [
                'context' => $this->buildContext(),
                'args' => [
                    'USER_ID' => (string) $this->userId(),
                    'GROUP_ID' => (string) $this->groupId(),
                ],
            ],
            // Rebuild on every up so a changed version takes effect. An
            // unchanged build is cached.
            'pull_policy' => 'build',
            'restart' => 'unless-stopped',
            'volumes' => $this->mounts(),
            // Steps and `docker exec` start in the app, wherever the project
            // is mounted.
            'working_dir' => self::APP_DIR,
            'environment' => [
                self::SERVERS[$this->option('server')] => $this->documentRoot(),
                // The proxy terminates TLS and connects over HTTP on 8080.
                'SSL_MODE' => 'off',
            ],
            'labels' => $this->route(8080),
        ];
    }

    public function prepare(): void
    {
        $file = basename($this->stack->config()->file());
        $install = $this->installInstructions();

        // Create the app folder and the project's mount point in it as the
        // host user. Docker would create them owned by root on Linux.
        if ($this->projectPath() !== null) {
            Files::ensureDirectory($this->directory('data').'/'.$this->projectPath());
        }

        Files::put($this->directory('build').'/Dockerfile', <<<DOCKERFILE
        # Generated by flight, do not edit. This file is overwritten on every run,
        # change services.{$this->name} in {$file} instead.

        FROM {$this->image()}

        USER root

        ARG USER_ID
        ARG GROUP_ID

        RUN docker-php-serversideup-set-id www-data \$USER_ID:\$GROUP_ID && \\
            docker-php-serversideup-set-file-permissions --owner \$USER_ID:\$GROUP_ID
        {$install}
        USER www-data

        DOCKERFILE);
    }

    /**
     * The extensions and tools to add to the image, run as root.
     */
    protected function installInstructions(): string
    {
        $instructions = [];

        if ($this->option('extensions') !== []) {
            $instructions[] = 'RUN install-php-extensions '.implode(' ', $this->option('extensions'));
        }

        if ($this->option('wp_cli')) {
            $instructions[] = 'ADD --chmod=755 '.self::WP_CLI.' /usr/local/bin/wp';
        }

        return implode('', array_map(fn (string $instruction): string => "\n{$instruction}\n", $instructions));
    }

    public function image(): string
    {
        return "serversideup/php:{$this->option('version')}-{$this->option('server')}";
    }

    /**
     * The project is the app, unless project_path places it inside an app
     * kept in .flight/<service>/data, e.g. a theme inside WordPress.
     *
     * @return array<int, string>
     */
    protected function mounts(): array
    {
        if ($this->projectPath() === null) {
            return ['.:'.self::APP_DIR];
        }

        return [
            $this->relativePath($this->directory('data')).':'.self::APP_DIR,
            '.:'.$this->appPath($this->projectPath()),
        ];
    }

    /**
     * Null when the project is the app.
     */
    protected function projectPath(): ?string
    {
        $path = trim((string) $this->option('project_path'), '/');

        return $path === '' || $path === '.' ? null : $path;
    }

    protected function buildContext(): string
    {
        return $this->relativePath($this->directory('build'));
    }

    protected function documentRoot(): string
    {
        return $this->appPath((string) $this->option('webroot'));
    }

    /**
     * A path relative to the app, in the container.
     */
    protected function appPath(string $path): string
    {
        $path = trim($path, '/');

        return $path === '' || $path === '.' ? self::APP_DIR : self::APP_DIR.'/'.$path;
    }

    /**
     * When running as root, keep www-data's own ID. Changing it to 0 would
     * run the web server as root.
     */
    protected function userId(): int
    {
        $id = function_exists('posix_getuid') ? posix_getuid() : 1000;

        return $id === 0 ? 33 : $id;
    }

    protected function groupId(): int
    {
        $id = function_exists('posix_getgid') ? posix_getgid() : 1000;

        return $id === 0 ? 33 : $id;
    }
}
