<?php

declare(strict_types=1);

namespace App\Services;

use App\Support\Files;
use Illuminate\Support\Str;

/**
 * A PHP web server based on serversideup/php.
 *
 * The image is built rather than pulled, because serversideup/php can only
 * change the www-data user's ID at build time. Matching it to the host user
 * keeps the mounted project writable on Linux and WSL.
 */
class Php extends Service
{
    public const array VERSIONS = ['8.1', '8.2', '8.3', '8.4', '8.5'];

    /**
     * Each server variation and the variable that sets its document root.
     */
    public const array SERVERS = [
        'fpm-nginx' => 'NGINX_WEBROOT',
        'fpm-apache' => 'APACHE_DOCUMENT_ROOT',
        'frankenphp' => 'CADDY_SERVER_ROOT',
    ];

    protected const string APP_DIR = '/var/www/html';

    protected const string WP_CLI = 'https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar';

    protected function defaults(): array
    {
        return [
            'version' => '8.4',
            'server' => 'fpm-nginx',
            'webroot' => 'public',
            'extensions' => [],
            'wp_cli' => false,
        ];
    }

    protected function rules(): array
    {
        return [
            'version' => ['required', 'in:'.implode(',', self::VERSIONS)],
            'server' => ['required', 'in:'.implode(',', array_keys(self::SERVERS))],
            'webroot' => ['string', 'regex:#^(?!/)(?!.*\.\.)[A-Za-z0-9._/-]*$#'],
            'extensions' => ['list'],
            'extensions.*' => ['string', 'regex:/^[a-z0-9_]+$/'],
            'wp_cli' => ['boolean'],
        ];
    }

    protected function messages(): array
    {
        return [
            'webroot.regex' => 'Expected a path inside the project, such as "public".',
            'extensions.*.regex' => 'Expected an extension name such as "mysqli".',
        ];
    }

    public static function routes(): bool
    {
        return true;
    }

    /**
     * An unquoted `version: 8.4` parses as a float.
     */
    protected function normalize(array $options): array
    {
        if (is_float($options['version']) || is_int($options['version'])) {
            $options['version'] = sprintf('%.1f', $options['version']);
        }

        return $options;
    }

    public function definition(): array
    {
        return [
            'build' => [
                'context' => $this->buildContext(),
                'args' => [
                    'USER_ID' => (string) $this->userId(),
                    'GROUP_ID' => (string) $this->groupId(),
                ],
            ],
            // Rebuild on every up so a changed version takes effect. An
            // unchanged build is cached.
            'pull_policy' => 'build',
            'restart' => 'unless-stopped',
            'volumes' => ['.:'.self::APP_DIR],
            'environment' => [
                self::SERVERS[$this->option('server')] => $this->documentRoot(),
                // The proxy terminates TLS and connects over HTTP on 8080.
                'SSL_MODE' => 'off',
            ],
            'labels' => $this->route(8080),
        ];
    }

    public function prepare(): void
    {
        $file = basename($this->stack->config()->file());
        $install = $this->installInstructions();

        Files::put($this->stack->filesDirectory().'/'.$this->name.'/Dockerfile', <<<DOCKERFILE
        # Generated by flight, do not edit. This file is overwritten on every run,
        # change services.{$this->name} in {$file} instead.

        FROM {$this->image()}

        USER root

        ARG USER_ID
        ARG GROUP_ID

        RUN docker-php-serversideup-set-id www-data \$USER_ID:\$GROUP_ID && \\
            docker-php-serversideup-set-file-permissions --owner \$USER_ID:\$GROUP_ID
        {$install}
        USER www-data

        DOCKERFILE);
    }

    /**
     * The extensions and tools to add to the image, run as root.
     */
    protected function installInstructions(): string
    {
        $instructions = [];

        if ($this->option('extensions') !== []) {
            $instructions[] = 'RUN install-php-extensions '.implode(' ', $this->option('extensions'));
        }

        if ($this->option('wp_cli')) {
            $instructions[] = 'ADD --chmod=755 '.self::WP_CLI.' /usr/local/bin/wp';
        }

        return implode('', array_map(fn (string $instruction): string => "\n{$instruction}\n", $instructions));
    }

    public function image(): string
    {
        return "serversideup/php:{$this->option('version')}-{$this->option('server')}";
    }

    /**
     * Relative to the compose project directory, e.g. "./.flight/php".
     */
    protected function buildContext(): string
    {
        $files = ltrim(Str::after($this->stack->filesDirectory(), $this->stack->directory()), '/');

        return './'.ltrim($files.'/'.$this->name, '/');
    }

    protected function documentRoot(): string
    {
        $webroot = trim((string) $this->option('webroot'), '/');

        return $webroot === '' || $webroot === '.'
            ? self::APP_DIR
            : self::APP_DIR.'/'.$webroot;
    }

    /**
     * When running as root, keep www-data's own ID. Changing it to 0 would
     * run the web server as root.
     */
    protected function userId(): int
    {
        $id = function_exists('posix_getuid') ? posix_getuid() : 1000;

        return $id === 0 ? 33 : $id;
    }

    protected function groupId(): int
    {
        $id = function_exists('posix_getgid') ? posix_getgid() : 1000;

        return $id === 0 ? 33 : $id;
    }
}
