<?php

declare(strict_types=1);

namespace App\Stacks;

use App\Services\ProjectService;
use App\Support\Files;
use App\Support\GlobalConfig;
use App\Support\ProjectConfig;
use Illuminate\Contracts\Container\Container;

/**
 * The services a project's flight.yml asks for. Generated files go in
 * .flight, but the project root is the compose project directory, so `.` in
 * a volume is the project root.
 */
class ProjectStack extends Stack
{
    /** @var array<int, ProjectService>|null */
    protected ?array $services = null;

    public function __construct(
        protected ProjectConfig $project,
        protected GlobalConfig $config,
        protected Container $container,
    ) {}

    public function project(): ProjectConfig
    {
        return $this->project;
    }

    /**
     * Prefixed, so a project named "flight" can't collide with the global
     * stack.
     */
    public function name(): string
    {
        return 'flight-'.$this->project->name();
    }

    public function directory(): string
    {
        return $this->project->root();
    }

    public function composeFile(): string
    {
        return $this->project->composeFile();
    }

    public function overrideFile(): ?string
    {
        return $this->project->overrideFile();
    }

    public function composeNote(): string
    {
        return 'change flight.yml, or add your own services to .flight/compose.override.yaml.';
    }

    /**
     * Keep generated files out of git without touching the project's own
     * .gitignore. The override file belongs to the user and can be committed.
     */
    public function prepare(): void
    {
        Files::put(
            $this->project->directory().'/.gitignore',
            "# Generated by flight.\n*\n!compose.override.yaml\n",
        );
    }

    /**
     * The first routed service is served at <project>.<domain>, the others at
     * <project>-<service>.<domain>. Both are one level under the domain,
     * which is all the wildcard certificate covers.
     *
     * @return array<int, ProjectService>
     */
    public function services(): array
    {
        if ($this->services !== null) {
            return $this->services;
        }

        $types = (array) config('flight.project_services');
        $project = $this->project->name();
        $routed = 0;

        $services = [];

        foreach ($this->project->services() as $name => $options) {
            $type = $options['type'];

            if (! is_string($type) || ! isset($types[$type])) {
                throw $this->project->invalid(
                    'Expected one of: '.implode(', ', array_keys($types)).'.',
                    "services.{$name}.type",
                );
            }

            /** @var class-string<ProjectService> $class */
            $class = $types[$type];

            $label = $class::routes()
                ? ($routed++ === 0 ? $project : $project.'-'.$name)
                : null;

            $services[] = $this->container->make($class, [
                'name' => (string) $name,
                'options' => $options,
                'label' => $label,
            ]);
        }

        $this->ensureUniqueHostnames($services);

        return $this->services = $services;
    }

    /**
     * Building the services validates their options.
     */
    public function validate(): void
    {
        $this->services();
    }

    /**
     * Otherwise Traefik would pick one of the services at random.
     *
     * @param  array<int, ProjectService>  $services
     */
    protected function ensureUniqueHostnames(array $services): void
    {
        $claimed = [];

        foreach ($services as $service) {
            foreach ($service->hostnames() as $hostname) {
                if (isset($claimed[$hostname])) {
                    throw $this->project->invalid(
                        "Expected {$hostname} to be served once, but services.{$claimed[$hostname]} already serves it.",
                        "services.{$service->name()}.hostnames",
                    );
                }

                $claimed[$hostname] = $service->name();
            }
        }
    }

    public function environment(): array
    {
        return [
            ...$this->config->environment(),
            'FLIGHT_PROJECT' => $this->project->name(),
            // The project's .env belongs to the application, not to compose.
            'COMPOSE_DISABLE_ENV_FILE' => '1',
        ];
    }
}
