<?php

declare(strict_types=1);

namespace App\Support;

use App\Exceptions\FlightException;
use Illuminate\Support\Str;

/**
 * The settings in a project's flight.yml.
 */
class ProjectConfig extends StackConfig
{
    public const string FILE = 'flight.yml';

    protected ?string $root = null;

    /**
     * The directory containing flight.yml, found by searching up from the
     * current directory, so commands work anywhere inside the project.
     */
    public function root(): string
    {
        if ($this->root !== null) {
            return $this->root;
        }

        $directory = (string) getcwd();

        while (! is_file($directory.'/'.self::FILE)) {
            $parent = dirname($directory);

            if ($parent === $directory) {
                throw FlightException::make(
                    'No '.self::FILE.' found in '.getcwd().' or any parent directory.',
                    'Create a '.self::FILE.' in your project root that lists the services it needs.',
                );
            }

            $directory = $parent;
        }

        return $this->root = $directory;
    }

    public function file(): string
    {
        return $this->root().'/'.self::FILE;
    }

    /**
     * The project root, so `.` in a volume is the project root.
     */
    public function directory(): string
    {
        return $this->root();
    }

    public function filesDirectory(): string
    {
        return $this->root().'/.flight';
    }

    public function name(): string
    {
        return $this->load()['name'];
    }

    /**
     * Prefixed, so a project named "flight" can't collide with the global
     * stack.
     */
    public function stackName(): string
    {
        return 'flight-'.$this->name();
    }

    public function composeNote(): string
    {
        return 'change flight.yml, or add your own services to .flight/compose.override.yaml.';
    }

    /**
     * Keep generated files out of git without touching the project's own
     * .gitignore. The override file belongs to the user and can be committed.
     */
    public function prepare(): void
    {
        Files::put(
            $this->filesDirectory().'/.gitignore',
            "# Generated by flight.\n*\n!compose.override.yaml\n",
        );
    }

    public function environment(): array
    {
        return [
            'FLIGHT_PROJECT' => $this->name(),
            // The project's .env belongs to the application, not to compose.
            'COMPOSE_DISABLE_ENV_FILE' => '1',
        ];
    }

    /**
     * The first routed service is served at <project>.<domain>, the others
     * at <project>-<service>.<domain>. Both are one level under the domain,
     * which is all the wildcard certificate covers.
     */
    public function label(string $service, int $routed): string
    {
        return $routed === 0 ? $this->name() : $this->name().'-'.$service;
    }

    protected function recipeName(array $settings): ?string
    {
        return $settings['recipe'] ?? null;
    }

    protected function withDefaults(array $settings): array
    {
        $settings['name'] ??= Str::slug(basename($this->root()));

        return $settings;
    }

    protected function rules(): array
    {
        return [
            'name' => ['required', 'string', 'regex:/^[a-z0-9][a-z0-9-]*$/'],
            'recipe' => ['nullable', 'string', 'in:'.implode(',', $this->recipes())],
            'services' => ['nullable', 'required_without:recipe', 'array'],
        ];
    }

    protected function messages(): array
    {
        return [
            'name.required' => 'Expected name to be set, or the directory name to contain a letter or digit.',
            'name.regex' => 'Expected a lowercase name such as "myapp"; it becomes myapp.<domain>.',
            'recipe.in' => 'Expected recipe to be one of: '.implode(', ', $this->recipes()).'.',
            'services.required_without' => 'Expected services to list at least one service, such as `php: {}`, or a recipe such as "laravel".',
        ];
    }

    /**
     * @return array<int, string>
     */
    protected function recipes(): array
    {
        return array_keys((array) config('flight.recipes'));
    }
}
