<?php

declare(strict_types=1);

namespace App\Support;

use App\Exceptions\FlightException;
use App\Recipes\Recipe;
use App\Services\PhpService;
use Illuminate\Contracts\Container\Container;
use Illuminate\Support\Facades\Validator;
use Symfony\Component\Yaml\Exception\ParseException;
use Symfony\Component\Yaml\Yaml;

/**
 * A stack's YAML file: a few settings, an app and services, merged over a
 * recipe. Only the shape of each service is checked here; each service
 * validates its own options.
 */
abstract class StackConfig
{
    public const string APP = 'app';

    protected ?array $settings = null;

    protected ?Recipe $recipe = null;

    protected ?array $ownComposeFiles = null;

    public function __construct(protected Container $container) {}

    abstract public function file(): string;

    abstract public function stackName(): string;

    abstract public function directory(): string;

    public function filesDirectory(): string
    {
        return $this->directory().'/.flight';
    }

    abstract public function label(string $service): string;

    /**
     * For the settings other than the services.
     */
    abstract protected function rules(): array;

    /**
     * As written: a name, a mapping of one name to its options, or null.
     */
    abstract protected function recipeSetting(array $settings): mixed;

    protected function messages(): array
    {
        return [];
    }

    protected function withDefaults(array $settings): array
    {
        return $settings;
    }

    public function composeFile(): string
    {
        return $this->filesDirectory().'/compose.yaml';
    }

    public function composeNote(): string
    {
        return 'change '.basename($this->file()).', or list your own compose files under `compose` in it.';
    }

    public function prepare(): void
    {
        Files::put($this->filesDirectory().'/.gitignore', "# Generated by flight.\n*\n");
    }

    /**
     * Variables compose files can use.
     */
    public function environment(): array
    {
        return [];
    }

    /**
     * The files listed under `compose` that exist. They run after the
     * generated file, so they can change what Flight generates.
     */
    public function ownComposeFiles(): array
    {
        if ($this->ownComposeFiles !== null) {
            return $this->ownComposeFiles;
        }

        $existing = [];

        foreach ($this->load()['compose'] ?? [] as $i => $file) {
            $path = $this->directory().'/'.$file['path'];

            if (is_file($path)) {
                $existing[] = $path;
            } elseif ($file['required']) {
                throw $this->invalid("Expected {$file['path']} to exist, or to be marked `required: false`.", "compose.{$i}");
            }
        }

        return $this->ownComposeFiles = $existing;
    }

    /**
     * The other stacks join the shared network as an external network.
     */
    public function ownsNetwork(): bool
    {
        return false;
    }

    public function recipe(): ?Recipe
    {
        $this->load();

        return $this->recipe;
    }

    public function services(): array
    {
        return $this->load()['services'];
    }

    protected function get(string $key): mixed
    {
        return $this->load()[$key] ?? null;
    }

    public function load(): array
    {
        if ($this->settings !== null) {
            return $this->settings;
        }

        $settings = $this->composeShorthand($this->withDefaults($this->read()));

        $this->validate($settings);

        $this->recipe = $this->makeRecipe($this->recipeSetting($settings));

        // A string is short for its type: `db: mariadb:11.8`.
        $shorthand = fn (mixed $entry): mixed => is_string($entry) ? ['type' => $entry] : $entry;

        $services = array_map($shorthand, (array) ($settings['services'] ?? []));
        $file = $shorthand($settings[self::APP] ?? null);

        foreach ($services as $name => $options) {
            $this->ensureRecipeType("services.{$name}", $this->recipe?->services()[$name] ?? null, $options);
        }

        $this->ensureRecipeType(self::APP, $this->recipe?->app(), $file);

        $merged = $this->merge($this->recipe?->services() ?? [], $services);

        if (array_key_exists(self::APP, $merged)) {
            throw $this->invalid('Expected another name; "app" is your app, set at the top level as `app:`.', 'services.'.self::APP);
        }

        if ($file !== null && ! $this->isMap($file)) {
            throw $this->invalid('Expected app to be a type such as `php:8.4`, or a mapping with a type.', self::APP);
        }

        if ($this->recipe?->app() !== null || $file !== null) {
            $merged = [self::APP => $this->merge($this->recipe?->app() ?? [], (array) $file), ...$merged];
        }

        $services = [];

        foreach ($merged as $name => $options) {
            $services[$name] = $this->service((string) $name, $options);
        }

        return $this->settings = [...$settings, 'services' => $services];
    }

    /**
     * Keep the recipe's type, so the recipe's options still fit: `php:8.5`
     * over the recipe's `php` is fine, `mariadb` is not.
     */
    protected function ensureRecipeType(string $path, mixed $recipe, mixed $file): void
    {
        $base = fn (mixed $options): ?string => is_string($options['type'] ?? null)
            ? explode(':', $options['type'])[0]
            : null;

        $expected = is_array($recipe) ? $base($recipe) : null;
        $actual = is_array($file) ? $base($file) : null;

        if ($expected !== null && $actual !== null && $expected !== $actual) {
            throw $this->invalid("Expected {$expected}, as set by the {$this->recipe?->name()} recipe; you can change its version, such as `{$expected}:<version>`.", "{$path}.type");
        }
    }

    /**
     * The version is split from the type: `type: mariadb:11.8` becomes the
     * type "mariadb" and the version "11.8".
     */
    protected function service(string $name, mixed $options): array
    {
        $app = $name === self::APP;
        $path = $app ? self::APP : "services.{$name}";
        $example = $app ? 'php:8.4' : 'mariadb:11.8';

        if (! $app && ! preg_match('/^[a-z0-9][a-z0-9_-]*$/', $name)) {
            throw $this->invalid('Expected a lowercase service name such as "db".', $path);
        }

        if (! $this->isMap($options)) {
            throw $this->invalid("Expected a type such as `{$example}`, or a mapping with a type.", $path);
        }

        if (array_key_exists('version', $options)) {
            throw $this->invalid("Expected the version in the type, such as `type: {$example}`.", "{$path}.version");
        }

        $types = $app ? (array) config('flight.app_types') : array_keys((array) config('flight.services'));
        $type = $options['type'] ?? null;

        if (! is_string($type) || ! preg_match('/^([a-z0-9_-]+)(?::([A-Za-z0-9._-]+))?$/', $type, $match) || ! in_array($match[1], $types, true)) {
            throw $this->invalid("Expected a type such as `{$example}`, one of: ".implode(', ', $types).'.', "{$path}.type");
        }

        unset($options['type']);

        return ['type' => $match[1], ...(isset($match[2]) ? ['version' => $match[2]] : []), ...$options];
    }

    protected function read(): array
    {
        if (! is_file($this->file())) {
            return [];
        }

        try {
            $parsed = Yaml::parseFile($this->file());
        } catch (ParseException $e) {
            throw FlightException::make('Could not parse '.$this->file().'.', $e->getMessage());
        }

        if ($parsed !== null && ! is_array($parsed)) {
            throw $this->invalid('Expected a mapping of settings.');
        }

        return (array) $parsed;
    }

    protected function makeRecipe(mixed $setting): ?Recipe
    {
        if ($setting === null) {
            return null;
        }

        if (is_string($setting)) {
            [$name, $options] = [$setting, []];
        } elseif ($this->isMap($setting) && count($setting) === 1) {
            $name = (string) array_key_first($setting);
            $options = $setting[$name] ?? [];
        } else {
            throw $this->invalid('Expected a recipe such as "laravel", or one recipe with its options, such as `laravel: {}`.', 'recipe');
        }

        $recipes = (array) config('flight.recipes');

        if (! isset($recipes[$name])) {
            throw $this->invalid('Expected recipe to be one of: '.implode(', ', array_keys($recipes)).'.', 'recipe');
        }

        if (! $this->isMap($options)) {
            throw $this->invalid('Expected a mapping of options.', "recipe.{$name}");
        }

        return $this->container->make($recipes[$name], ['config' => $this, 'name' => $name, 'options' => $options]);
    }

    /**
     * Mappings merge key by key, anything else is replaced. A null option,
     * such as a bare `php:`, keeps the recipe's value.
     */
    protected function merge(array $base, array $override): array
    {
        foreach ($override as $key => $value) {
            $current = $base[$key] ?? null;

            if ($value === null && array_key_exists($key, $base)) {
                continue;
            }

            $base[$key] = $this->isMap($current) && $this->isMap($value)
                ? $this->merge($current, $value)
                : $value;
        }

        return $base;
    }

    protected function isMap(mixed $value): bool
    {
        return is_array($value) && ($value === [] || ! array_is_list($value));
    }

    protected function composeShorthand(array $settings): array
    {
        if (is_array($settings['compose'] ?? null)) {
            $settings['compose'] = array_map(fn (mixed $file): mixed => match (true) {
                is_string($file) => ['path' => $file, 'required' => true],
                is_array($file) => [...$file, 'required' => $file['required'] ?? true],
                default => $file,
            }, $settings['compose']);
        }

        return $settings;
    }

    protected function validate(array $settings): void
    {
        $rules = [
            'services' => ['nullable', 'array'],
            ...$this->rules(),
            'compose' => ['nullable', 'list'],
            'compose.*' => ['array:path,required'],
            'compose.*.path' => ['required', 'string', 'regex:'.PhpService::PATH],
            'compose.*.required' => ['boolean'],
        ];

        $topLevel = array_filter(array_keys($rules), fn (string $key): bool => ! str_contains($key, '.'));

        foreach (array_keys($settings) as $key) {
            if (! in_array($key, $topLevel, true)) {
                throw $this->invalid('Expected one of: '.implode(', ', $topLevel).'.', (string) $key);
            }
        }

        // Name attributes after the YAML keys, e.g. "http_port" instead of
        // "http port".
        $keys = array_filter(array_keys($rules), fn (string $key): bool => ! str_contains($key, '*'));

        $validator = Validator::make($settings, $rules, [
            'services.array' => 'Expected services to be a mapping of names to types, such as `db: mariadb:11.8`.',
            'compose.list' => 'Expected the compose files to run, such as [compose.yml].',
            'compose.*.array' => 'Expected a file such as "compose.yml", or one that may be missing, such as `{path: compose.override.yml, required: false}`.',
            'compose.*.path.regex' => 'Expected a path inside the folder of '.basename($this->file()).', such as "compose.yml".',
            ...$this->messages(),
        ], attributes: array_combine($keys, $keys));

        if ($validator->fails()) {
            $key = (string) array_key_first($validator->errors()->messages());

            throw $this->invalid((string) $validator->errors()->first($key), $key);
        }

        $services = $settings['services'] ?? [];

        if ($services !== [] && array_is_list($services)) {
            throw $this->invalid('Expected services to be a mapping of names to types, such as `db: mariadb:11.8`.', 'services');
        }
    }

    public function invalid(string $hint, ?string $key = null): FlightException
    {
        return FlightException::make(
            $key === null ? 'Invalid '.$this->file().'.' : "Invalid \"{$key}\" in ".$this->file().'.',
            $hint,
        );
    }
}
