<?php

declare(strict_types=1);

namespace App\Support;

use App\Exceptions\FlightException;
use App\Services\Routed;
use App\Services\Service;
use App\Stacks\Stack;
use Closure;
use Illuminate\Contracts\Process\InvokedProcess;
use Illuminate\Support\Facades\Process;

/**
 * Shares a service at a temporary https://<words>.trycloudflare.com URL
 * through a Cloudflare quick tunnel, which needs no Cloudflare account.
 *
 * The tunnel runs in a container on the stack's network, from an image Flight
 * builds: cloudflared next to nginx. nginx sends the service its own hostname
 * and puts the public one back in what the service returns, so apps that only
 * know their own URL, such as WordPress, work unchanged.
 */
class Tunnel
{
    protected const string IMAGE = 'flight-share';

    protected const string CLOUDFLARED = 'cloudflare/cloudflared:2026.9.1';

    protected const string NGINX = 'nginx:1.30-alpine';

    /**
     * The pattern of the public URL, which isn't api.trycloudflare.com,
     * mentioned when cloudflared fails.
     */
    protected const string URL = '#https://(?!api\.)[a-z0-9-]+\.trycloudflare\.com#';

    protected const string DNS = 'https://cloudflare-dns.com/dns-query';

    public function __construct(protected GlobalConfig $global) {}

    /**
     * Docker caches the image, so only the first build takes time.
     */
    public function build(?Closure $output = null): void
    {
        $directory = $this->global->shareDirectory();

        Files::put($directory.'/Dockerfile', $this->dockerfile());
        Files::put($directory.'/entrypoint.sh', $this->entrypoint());
        Files::put($directory.'/share.conf.template', $this->nginxConfig());

        $result = Process::timeout(600)->run(['docker', 'build', '--quiet', '--tag', self::IMAGE, $directory], $output);

        if ($result->failed()) {
            throw FlightException::fromProcess($result, 'Could not build the image for the tunnel.');
        }
    }

    /**
     * With $rewrite, the service sees its own hostname instead of the public
     * one.
     */
    public function start(Stack $stack, Service&Routed $service, bool $rewrite, Closure $output): InvokedProcess
    {
        return Process::forever()->start([
            'docker', 'run', '--rm',
            // So a second share of the same service is refused.
            '--name', $stack->name().'-'.$service->name().'-share',
            '--network', $stack->network(),
            '--env', 'UPSTREAM='.$service->origin(),
            ...($rewrite ? ['--env', 'LOCAL_HOST='.$service->hostnames()[0]] : []),
            self::IMAGE,
        ], $output);
    }

    public static function url(string $log): ?string
    {
        return preg_match(self::URL, $log, $match) ? $match[0] : null;
    }

    /**
     * Asked of Cloudflare directly: a local resolver asked too early
     * remembers for a while that the hostname doesn't exist.
     */
    public function resolves(string $url): bool
    {
        $response = @file_get_contents(self::DNS.'?type=A&name='.parse_url($url, PHP_URL_HOST), false, stream_context_create([
            'http' => ['header' => 'Accept: application/dns-json', 'timeout' => 2],
        ]));

        return is_string($response) && str_contains($response, '"Answer"');
    }

    protected function dockerfile(): string
    {
        $nginx = self::NGINX;
        $cloudflared = self::CLOUDFLARED;

        return <<<DOCKERFILE
        # Generated by flight, do not edit. This file is overwritten on every
        # run of `flight share`.

        FROM {$nginx}

        COPY --from={$cloudflared} /usr/local/bin/cloudflared /usr/local/bin/cloudflared

        # Log only what goes wrong.
        RUN sed -i 's/^error_log .*/error_log stderr warn;/' /etc/nginx/nginx.conf
        ENV NGINX_ENTRYPOINT_QUIET_LOGS=1

        COPY share.conf.template /etc/nginx/templates/default.conf.template
        COPY entrypoint.sh /entrypoint.sh

        ENTRYPOINT ["sh", "/entrypoint.sh"]

        DOCKERFILE;
    }

    /**
     * cloudflared runs in the foreground, so stopping it stops the container,
     * nginx included.
     */
    protected function entrypoint(): string
    {
        return <<<'SH'
        #!/bin/sh
        set -e

        url="$UPSTREAM"

        # Fill in the nginx config from the environment and start nginx in
        # the background.
        if [ -n "$LOCAL_HOST" ]; then
            /docker-entrypoint.sh nginx
            url=http://localhost:80
        fi

        # The service's certificate is self-signed.
        exec cloudflared tunnel --no-autoupdate --protocol http2 --no-tls-verify --url "$url"

        SH;
    }

    /**
     * Only the variables set on the container are filled in, so nginx's own,
     * such as $host, the public hostname, are left alone.
     */
    protected function nginxConfig(): string
    {
        return <<<'NGINX'
        server {
            listen 80;

            access_log off;
            client_max_body_size 0;

            location / {
                proxy_pass ${UPSTREAM};
                proxy_http_version 1.1;
                proxy_read_timeout 300s;

                proxy_set_header Host ${LOCAL_HOST};
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto https;
                # sub_filter can only replace text in uncompressed responses.
                proxy_set_header Accept-Encoding "";

                proxy_redirect https://${LOCAL_HOST}/ https://$host/;
                proxy_redirect http://${LOCAL_HOST}/ https://$host/;
                proxy_cookie_domain ${LOCAL_HOST} $host;

                # Links such as https://… and //…, also escaped as in JSON.
                sub_filter_once off;
                sub_filter_types text/css text/javascript application/javascript application/json application/xml text/xml;
                sub_filter '//${LOCAL_HOST}' '//$host';
                sub_filter '\/\/${LOCAL_HOST}' '\/\/$host';
            }
        }

        NGINX;
    }
}
