<?php

declare(strict_types=1);

namespace App\Support;

use Symfony\Component\Yaml\Yaml;

class YamlFile
{
    public static function write(string $path, array $data, string $note): void
    {
        $comment = implode("\n", array_map(fn (string $line): string => rtrim('# '.$line), explode("\n", $note)));

        Files::put(
            $path,
            "---\n".
            "# Generated by flight, do not edit. This file is overwritten on every run,\n".
            $comment."\n\n".
            Yaml::dump($data, 6, 2)
        );
    }
}
